name: Sync XiaoyaApi

on:
  workflow_dispatch:
    inputs:
      logLevel:
        description: 'Log level'     
        required: true
        default: 'warning'
#  schedule:
#    - cron: '0 0 * * *'

env:
  TZ: Asia/Shanghai

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout
        uses: actions/checkout@main

      - name: Download files
        run: |
          wget --user-agent="Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppelWebKit/537.36 (KHTML, like Gecko) Chrome/87.0.4280.88 Safari/537.36" -T 5 -t 2 -q http://docker.xiaoya.pro/update/version.txt
          wget --user-agent="Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppelWebKit/537.36 (KHTML, like Gecko) Chrome/87.0.4280.88 Safari/537.36" -T 5 -t 2 -q http://docker.xiaoya.pro/update/update.zip
          wget --user-agent="Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppelWebKit/537.36 (KHTML, like Gecko) Chrome/87.0.4280.88 Safari/537.36" -T 5 -t 2 -q http://docker.xiaoya.pro/update/index.zip
          sudo timedatectl set-timezone "$TZ"
          echo "DATE=$(date "+%Y-%m-%d %H:%M:%S")" >> $GITHUB_ENV
          
      - name:  Upload files to Release
        uses: ncipollo/release-action@v1
        with:
          tag: XiaoyaApi
          allowUpdates: true
          removeArtifacts: true
          artifacts: "version.txt,update.zip,index.zip"
          token: ${{ secrets.GITHUB_TOKEN }}
          body: |
            - Docker xiaoyaliu/alist的api接口
            Time：${{ env.DATE }}